name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: timmoth
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Europe/London
          plugin_introduction: yes
          plugin_habits: yes
          plugin_languages: yes
          plugin_traffic: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_repositories: 100
          plugin_repositories_affiliations: owner,contributor
          repositories_affiliations: owner,contributor
          plugin_leetcode: yes
          plugin_leetcode_user: timmoth
