name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: timmoth
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Europe/London
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_traffic: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          repositories_affiliations: owner,contributor
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_leetcode: yes
          plugin_leetcode_user: timmoth
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: timmoth_j
          plugin_tweets_limit: 5
