on: 
  workflow_dispatch:
name: Scrape File
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Download the file
        with:
          url: "https://i7fwmju8w6.execute-api.eu-west-1.amazonaws.com/dev/image.png"
          target: assets
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Changed files
